# $OpenBSD: Makefile.bsd-wrapper,v 1.8 2009/06/04 00:40:05 matthieu Exp $
.include <bsd.xconf.mk>

SHARED_LIBS=	Xfont 8.0

.if ${XENOCARA_HAVE_SHARED_LIBS:L} == "no"
CONFIGURE_ARGS+= --disable-loadable-font-modules
.endif

.include <bsd.xorg.mk>
