# $OpenBSD: Makefile.bsd-wrapper,v 1.10 2010/01/17 20:48:49 matthieu Exp $
.include <bsd.xconf.mk>

SHARED_LIBS=	Xfont 9.0

CONFIGURE_ARGS+= --with-xmlto=no

.if ${XENOCARA_HAVE_SHARED_LIBS:L} == "no"
CONFIGURE_ARGS+= --disable-loadable-font-modules
.endif

.include <bsd.xorg.mk>
