# $OpenBSD: Makefile.bsd-wrapper,v 1.6 2007/09/08 16:24:20 matthieu Exp $

SHARED_LIBS=	Xfont 7.0

.if ${MACHINE} == landisk || ${MACHINE} == vax
CONFIGURE_ARGS+= --disable-loadable-font-modules
.endif

.if ${MACHINE} == landisk || ${MACHINE} == vax
CONFIGURE_ARGS+= --disable-loadable-font-modules
.endif

.include <bsd.xorg.mk>
