# $OpenBSD: Makefile,v 1.2 2010/04/27 19:58:25 matthieu Exp $

HEADERS_SUBDIR=	X11/extensions/
HEADERS=	xf86dga.h xf86dgastr.h xf86dga1const.h xf86dga1str.h \
		xf86dga1proto.h xf86dgaconst.h xf86dgaproto.h

PKGCONFIG=	xf86dgaproto.pc

.include <bsd.xorg.mk>
