# $OpenBSD: Makefile.bsd-wrapper,v 1.7 2007/01/29 22:06:35 matthieu Exp $

DIST= ${.CURDIR}

CONFIGURE_ARGS=	--localstatedir=/var --sysconfdir=/etc/X11 \
		--with-xkb-path=/etc/X11/xkb \
		--with-xkb-output=/var/db/xkb \
		--with-module-dir=${LIBDIR}/modules \
		--with-mesa-source=${XENOCARA_TOP}/dist/Mesa \
		--enable-install-setuid --enable-privsep \
		--disable-dmx

.include <bsd.xorg.mk>
