.\" $Xorg: x11pcomp.man,v 1.4 2001/02/09 02:05:38 xorgcvs Exp $
.\" Copyright 1993, 1994, 1998  The Open Group
.\" 
.\" Permission to use, copy, modify, distribute, and sell this software and its
.\" documentation for any purpose is hereby granted without fee, provided that
.\" the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.
.\" 
.\" The above copyright notice and this permission notice shall be included
.\" in all copies or substantial portions of the Software.
.\" 
.\" THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
.\" OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
.\" MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
.\" IN NO EVENT SHALL THE OPEN GROUP BE LIABLE FOR ANY CLAIM, DAMAGES OR
.\" OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
.\" ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
.\" OTHER DEALINGS IN THE SOFTWARE.
.\" 
.\" Except as contained in this notice, the name of The Open Group shall
.\" not be used in advertising or otherwise to promote the sale, use or
.\" other dealings in this Software without prior written authorization
.\" from The Open Group.
.\"
.\" $XFree86: xc/programs/x11perf/x11pcomp.man,v 1.7 2001/01/27 18:21:07 dawes Exp $
.\"
.TH X11PERFCOMP 1 __xorgversion__
.SH NAME
x11perfcomp \- X11 server performance comparison program
.SH SYNTAX
.B x11perfcomp
[ \-r | \-ro ] [ \-l label_file ] files
.SH DESCRIPTION
The
.I x11perfcomp
program merges the output of several
.I x11perf(1)
runs into a nice tabular
format.  It takes the results in each file, fills in any missing test results if
necessary, and for each test shows the objects/second rate of each server.
If invoked with the -r or -ro options, it shows the relative performance 
of each server to the first server.
.PP
Normally,
.I x11perfcomp
uses the first file specified to determine which specific tests it should
report on.  Some (non-DEC :) servers may fail to perform
all tests.  In this case,
.I x11perfcomp
automatically substitutes in a rate of 0.0 objects/second. 
Since the first file
determines which tests to report on, this file must contain a superset of
the tests reported in the other files, else 
.I x11perfcomp
will fail.
.PP
You can provide an explicit list of tests to report on
by using the -l switch to specify a file of labels.  You can create a label
file by using the -label option in 
.I x11perf.
.SH OPTIONS
.I x11perfcomp
accepts the options listed below:
.TP 16
.B \-r
Specifies that the output should also include relative server
performance.
.TP 16
.B \-ro
Specifies that the output should include only relative server performance.
.TP 16
.B \-l label_file
Specifies a label file to use.
.SH X DEFAULTS
There are no X defaults used by this program.
.SH "SEE ALSO"
X(__miscmansuffix__), x11perf(1)
.SH AUTHORS
Mark Moraes wrote the original scripts to compare servers.
.br
Joel McCormack just munged them together a bit.
