/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define ENABLE_EGL 1

#define ENABLE_GLX 1

#define ENABLE_X11 1

#define EPOXY_PUBLIC __attribute__((visibility("default"))) extern

#define HAVE_KHRPLATFORM_H

#define PACKAGE_DATADIR "/usr/X11R6/share"

#define PACKAGE_LIBDIR "/usr/X11R6/lib"

#define PACKAGE_LIBEXECDIR "/usr/X11R6/libexec"

#define PACKAGE_LOCALEDIR "/usr/X11R6/share/locale"

#define PACKAGE_NAME "libepoxy"

#define PACKAGE_STRING "libepoxy-1.5.4"

#define PACKAGE_VERSION "1.5.4"

