# $OpenBSD: Makefile.bsd-wrapper,v 1.3 2019/06/19 19:26:36 matthieu Exp $
.include <bsd.xconf.mk>

SHARED_LIBS=	Xfont2 1.0

CONFIGURE_ARGS+= --disable-fc --with-xmlto=no --disable-devel-docs

.include <bsd.xorg.mk>
