# $OpenBSD: Makefile.bsd-wrapper,v 1.2 2018/05/26 07:51:00 matthieu Exp $
.include <bsd.xconf.mk>

SHARED_LIBS=	Xfont2 1.0

CONFIGURE_ARGS+= --with-xmlto=no --disable-devel-docs

.include <bsd.xorg.mk>
