/*
 * ZDI-CAN-30560: computeProps property buffer heap overflow
 *
 * The font has 40 duplicate MIN_SPACE properties. When the bitmap
 * scaler processes this font, computeProps writes 2 slots per scaledX
 * match into the fixed 70-slot property buffer, overflowing after 25
 * matches (50 slots + 20 XLFD slots = 70, then overflow).
 *
 * With the fix in bitscale.c, computeProps checks remaining buffer
 * capacity and silently skips properties that would overflow.
 *
 * The font is stored at pixel=10; loading at pixel=20 triggers the
 * scaling path through ComputeScaledProperties -> computeProps.
 *
 * Test font: test/data/props/evil-props.pcf
 * Generated by: test/gen_evil_pcf_props.py
 */

/*
 * Copyright (c) 2026, Red Hat, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#include "pcf-test-common.h"
#include <stdio.h>
#include <stdlib.h>

int
main(int argc, char **argv)
{
    xfont2_fpe_funcs_rec const **fpe_functions;
    int fpe_function_count;
    const char *builddir;
    char fontdir[512];

    builddir = getenv("builddir");
    if (!builddir)
        builddir = ".";

    fpe_functions = pcf_test_init(&fpe_function_count);

    snprintf(fontdir, sizeof(fontdir), "%s/test/data/props", builddir);
    return pcf_test_open_font(fpe_functions,
                              "ZDI-CAN-30560-props",
                              fontdir,
                              "-evil-props-medium-r-normal--20-200-75-75-c-80-iso10646-1");
}
