# $OpenBSD: Makefile,v 1.1 2008/03/25 23:28:19 matthieu Exp $

HEADERS_SUBDIRS=	GL GL/internal
HEADERS_GL=		glxint.h glxmd.h glxproto.h glxtokens.h
HEADERS_GL_internal=	glcore.h
PKGCONFIG=		glproto.pc

.include <bsd.xorg.mk>
