#	$OpenBSD: Makefile,v 1.3 2009/05/22 16:53:05 matthieu Exp $

LIB=		xcb-screensaver

HEADERS=	screensaver.h

SRCS=		screensaver.c

PKGCONFIG=	xcb-screensaver.pc

.include <bsd.lib.mk>
.include <bsd.xorg.mk>
