.\" $XFree86: xc/programs/Xserver/hw/xfree86/input/void/void.man,v 1.1 2001/01/24 00:06:38 dawes Exp $ 
.\" shorthand for double quote that works everywhere.
.ds q \N'34'
.TH VOID __drivermansuffix__ __vendorversion__
.SH NAME
void \- null input driver
.SH SYNOPSIS
.nf
.B "Section \*qInputDevice\*q"
.BI "  Identifier \*q" idevname \*q
.B  "  Driver \*qvoid\*q"
\ \ ...
.B EndSection
.fi
.SH DESCRIPTION
.B void 
is an dummy/null __xservername__ input driver.  It doesn't connect to any
physical device, and it never delivers any events.  It functions as
both a pointer and keyboard device, and may be used as X server's core
pointer and/or core keyboard.  It's purpose is to allow the X server
to operate without a core pointer and/or core keyboard.
.SH CONFIGURATION DETAILS
Please refer to __xconfigfile__(__filemansuffix__) for general configuration
details and for options that can be used with all input drivers.  This
driver doesn't have any configuration options in addition to those.
.SH "SEE ALSO"
__xservername__(__appmansuffix__), __xconfigfile__(__filemansuffix__), xorgconfig(__appmansuffix__), Xserver(__appmansuffix__), X(__miscmansuffix__).
.SH AUTHORS
Authors include...
