#	$OpenBSD: Makefile,v 1.1.1.1 2009/06/06 17:55:01 matthieu Exp $

XKB_SUBDIR=	compat
DIR_DATA=	compat.dir

DATA =	accessx basic complete \
	default iso9995 \
	japan keypad ledcaps \
	lednum ledscroll level5 \
	misc mousekeys norepeat \
	olpc pc pc98 xfree86 \
	xtest README

.include <bsd.xorg.mk>
