#	$OpenBSD: Makefile.bsd-wrapper,v 1.5 2006/12/17 21:45:51 matthieu Exp $

SHARED_LIBS=	fontconfig 5.0

CONFIGURE_ARGS= --with-expat=${X11BASE} --sysconfdir=/etc \
	--mandir=${X11BASE}/man \
	--with-cache-dir=/var/cache/fontconfig \
	--with-default-fonts=${X11BASE}/lib/X11/fonts \
	--with-add-fonts=/usr/local/lib/X11/fonts \
	--disable-docs

.include <bsd.xorg.mk>
