#	$OpenBSD: Makefile,v 1.2 2006/11/27 19:56:35 matthieu Exp $
.include <bsd.xorg.mk>

INCSDIR=${X11BASE}/include/freetype2/freetype/config

INCS=	ftconfig.h ftheader.h ftmodule.h ftoption.h ftstdlib.h

