.\" shorthand for double quote that works everywhere.
.ds q \N'34'
.TH ATI __drivermansuffix__ __vendorversion__
.SH NAME
ati \- ATI video driver
.SH SYNOPSIS
.nf
.B "Section \*qDevice\*q"
.BI "  Identifier \*q"  devname \*q
.B  "  Driver \*qati\*q"
\ \ ...
.B EndSection
.fi
.SH DESCRIPTION
.B ati
is an __xservername__ wrapper driver for ATI video cards.  It autodetects
whether your hardware has a Radeon, Rage 128, or Mach64 or earlier class of
chipset, and loads the radeon(__drivermansuffix__),
r128(__drivermansuffix__), or mach64 driver as
appropriate.
.SH SUPPORTED HARDWARE
The
.B ati
driver supports Radeon, Rage 128, and Mach64 and earlier chipsets by loading
those drivers.  See those manpages for specific cards supported.
.SH CONFIGURATION DETAILS
Please refer to __xconfigfile__(__filemansuffix__) for general configuration
details, and the specific card driver for driver configuration details.
.SH "SEE ALSO"
__xservername__(__appmansuffix__), __xconfigfile__(__filemansuffix__), Xserver(__appmansuffix__), X(__miscmansuffix__), r128(__drivermansuffix__), radeon(__drivermansuffix__)
.SH AUTHORS
See the individual driver pages for authors.
