.\" $XFree86: xc/programs/Xserver/hw/xfree86/drivers/imstt/imstt.man,v 1.1 2001/01/24 00:06:20 dawes Exp $ 
.\" shorthand for double quote that works everywhere.
.ds q \N'34'
.TH IMSTT __drivermansuffix__ __vendorversion__
.SH NAME
imstt \- Integrated Micro Solutions Twin Turbo 128 driver
.SH SYNOPSIS
.nf
.B "Section \*qDevice\*q"
.BI "  Identifier \*q"  devname \*q
.B  "  Driver \*qimstt\*q"
\ \ ...
.B EndSection
.fi
.SH DESCRIPTION
.B imstt 
is an __xservername__ driver for Integrated Micro Solutions Twin Turbo 128 video chips.
THIS MAN PAGE NEEDS TO BE FILLED IN.
.SH SUPPORTED HARDWARE
The
.B imstt
driver supports...
.SH CONFIGURATION DETAILS
Please refer to __xconfigfile__(__filemansuffix__) for general configuration
details.  This section only covers configuration details specific to this
driver.
.SH "SEE ALSO"
__xservername__(__appmansuffix__), __xconfigfile__(__filemansuffix__), xorgconfig(__appmansuffix__), Xserver(__appmansuffix__), X(__miscmansuffix__)
.SH AUTHORS
Authors include: ...
