.\" $XFree86$
.\" shorthand for double quote that works everywhere.
.ds q \N'34'
.TH VOID __drivermansuffix__ __vendorversion__
.SH NAME
void \- null input driver
.SH SYNOPSIS
.nf
.B "Section \*qInputDevice\*q"
.BI "  Identifier \*q" idevname \*q
.B  "  Driver \*qmagictouch\*q"
\ \ ...
.B EndSection
.fi
.SH DESCRIPTION
.B magictouch
is an __xservername__ input driver.
.SH CONFIGURATION DETAILS
Please refer to __xconfigfile__(__filemansuffix__) for general configuration
details and for options that can be used with all input drivers.  This
driver doesn't have any configuration options in addition to those.
.SH "SEE ALSO"
__xservername__(__appmansuffix__), __xconfigfile__(__filemansuffix__), xf86cfg(__appmansuffix__), xorgconfig(__appmansuffix__), Xserver(__appmansuffix__), X(__miscmansuffix__).
.SH AUTHORS
Authors include...
