# $OpenBSD: Makefile.bsd-wrapper,v 1.3 2008/02/20 22:23:07 matthieu Exp $

SHARED_LIBS=	Xcursor 4.0

CONFIGURE_ARGS+=	--with-cursorpath="~/.icons:/usr/local/lib/X11/icons:${X11BASE}/share/icons:${X11BASE}/share/pixmaps"

.include <bsd.xorg.mk>
