#	$OpenBSD: Makefile,v 1.2 2006/11/27 19:56:35 matthieu Exp $
.include <bsd.xorg.mk>

INCSDIR=${X11BASE}/include/freetype2/freetype/internal/services

INCS=	svbdf.h svgldict.h svkern.h svmm.h svpfr.h svpostnm.h svpscmap.h \
	svpsinfo.h svsfnt.h svttcmap.h svtteng.h svwinfnt.h svxf86nm.h

.include "../../Makefile.inc"
