#!/bin/sh
#	$OpenBSD: gensetlist,v 1.2 2006/11/29 16:36:46 matthieu Exp $

arch=$MACHINE
listsdir=`pwd`/lists

setname=$1
Release=$2

if [ "$setname" = "xfont" ]; then
        arch=x11r7
fi

cat $listsdir/$setname/mi $listsdir/$setname/md.${arch} 
