#!/bin/sh
#	$OpenBSD: makelocatedb,v 1.2 2014/07/12 19:14:55 espie Exp $

# xy
RELEASE=$1

if [ "X${RELEASE}" = "X" ]; then
	echo "Usage: `basename $0` <OSREVISION>"
	exit 1
fi

pwd=`pwd`
listsdir=`pwd`/lists

lists=`sh ./genlists ${MACHINE}`

for setname in $lists; do
	(cd $pwd; sh gensetlist $setname) | \
	    sed -e "s,^\.,${setname}${RELEASE}:,"
done | sort | /usr/libexec/locate.mklocatedb
