#!/bin/sh
#	$OpenBSD: makelocatedb,v 1.3 2014/08/31 16:52:26 matthieu Exp $

# xy
RELEASE=$1

if [ "X${RELEASE}" = "X" ]; then
	echo "Usage: `basename $0` <OSREVISION>"
	exit 1
fi

pwd=`pwd`
listsdir=`pwd`/lists

for setname in xbase xetc xfont xserv xshare; do
	(cd $pwd; sh gensetlist $setname) | \
	    sed -e "s,^\.,${setname}${RELEASE}:,"
done | sort | /usr/libexec/locate.mklocatedb
