#!/bin/sh
#	$OpenBSD: maketars,v 1.3 2007/08/05 22:26:02 todd Exp $

# xy
RELEASE=$1
Release=$2
# x.y

if [ "X${RELEASE}" = "X" ]; then
	echo "Usage: `basename $0` <OSREVISION>"
	exit 1
fi

if [ "X${RELEASEDIR}" = "X" ]; then
	echo RELEASEDIR must be set
	exit 1
fi

if [ "X${DESTDIR}" = "X" ]; then
	echo DESTDIR must be set
	exit 1
fi

arch=${MACHINE}
pwd=`pwd`
listsdir=`pwd`/lists
tardir=$RELEASEDIR

TMPDIR=`mktemp -d /tmp/_maketarsx.XXXXXXXXXX`
trap 'rm -f $TMP1 $TMP2; rmdir $TMPDIR; exit 1' 1 15
TMP1=$TMPDIR/one
TMP2=$TMPDIR/two

lists=`sh ./genlists $arch`

cd $DESTDIR

for setname in $lists; do
	echo -n "${setname}: "
	(cd $pwd; sh gensetlist $setname $Release) | sort > $TMP1
	sed -n  '/^\.\/usr\/X11R6\/lib\/lib.*\.so\..*/{p;}' $TMP1 > $TMP2
	sed     '/^\.\/usr\/X11R6\/lib\/lib.*\.so\..*/d'    $TMP1 >> $TMP2
	pax -w -d < $TMP2 | gzip -9 > ${tardir}/${setname}${RELEASE}.tgz
	echo    "done."
done

echo    "done."
