#!/bin/sh
#	$OpenBSD: maketars,v 1.5 2014/05/03 15:18:26 todd Exp $

# xy
RELEASE=$1

if [ "X${RELEASE}" = "X" ]; then
	echo "Usage: `basename $0` <OSREVISION>"
	exit 1
fi

if [ "X${RELEASEDIR}" = "X" ]; then
	echo RELEASEDIR must be set
	exit 1
fi

if [ "X${DESTDIR}" = "X" ]; then
	echo DESTDIR must be set
	exit 1
fi

arch=${MACHINE}
pwd=`pwd`
listsdir=`pwd`/lists
tardir=$RELEASEDIR

TMPDIR=`mktemp -d /tmp/_maketarsx.XXXXXXXXXX` || exit 1
trap 'rm -f $TMP1 $TMP2; rmdir $TMPDIR' 0 1 15
TMP1=$TMPDIR/one
TMP2=$TMPDIR/two

lists=`sh ./genlists $arch`

cd $DESTDIR

for setname in $lists; do
	echo -n "${setname}: "
	(cd $pwd; sh gensetlist $setname) | sort > $TMP1
	sed -n  '/^\.\/usr\/X11R6\/lib\/lib.*\.so\..*/{p;}' $TMP1 > $TMP2
	sed     '/^\.\/usr\/X11R6\/lib\/lib.*\.so\..*/d'    $TMP1 >> $TMP2
	pax -w -d < $TMP2 | gzip -9 > ${tardir}/${setname}${RELEASE}.tgz
	echo    "done."
done

echo    "done."
