# $OpenBSD: Makefile,v 1.3 2010/05/10 20:02:59 matthieu Exp $

HEADERS_SUBDIR=	X11/extensions/
HEADERS=	dpmsconst.h dpmsproto.h ge.h geproto.h \
		lbx.h lbxproto.h \
		mitmiscconst.h mitmiscproto.h multibufconst.h multibufproto.h \
		secur.h securproto.h shapeconst.h shapeproto.h \
		shm.h shmproto.h syncconst.h syncproto.h \
		ag.h agproto.h cup.h cupproto.h dbe.h \
		dbeproto.h EVI.h EVIproto.h \
		xtestext1proto.h xtestext1const.h xtestconst.h xtestproto.h
PKGCONFIG=	xextproto.pc

.include <bsd.xorg.mk>
