#!/bin/sh
# Reassign ownership of the console to root, this should disallow
# assignment of console output to any random users's xterm
# $OpenBSD: TakeConsole,v 1.1 2016/10/23 08:30:37 matthieu Exp $
#
chmod 622 /dev/console
chown root /dev/console
if [ -c /dev/drm0 ]; then
    chown root /dev/drm0
fi
/usr/X11R6/bin/sessreg -d -l $DISPLAY -u /var/run/utmp -x /etc/X11/xenodm/Xservers $USER
