.\" Copyright 1988, 1998  The Open Group
.\"
.\" Permission to use, copy, modify, distribute, and sell this software and its
.\" documentation for any purpose is hereby granted without fee, provided that
.\" the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.
.\"
.\" The above copyright notice and this permission notice shall be included
.\" in all copies or substantial portions of the Software.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
.\" OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
.\" MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
.\" IN NO EVENT SHALL THE OPEN GROUP BE LIABLE FOR ANY CLAIM, DAMAGES OR
.\" OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
.\" ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
.\" OTHER DEALINGS IN THE SOFTWARE.
.\"
.\" Except as contained in this notice, the name of The Open Group shall
.\" not be used in advertising or otherwise to promote the sale, use or
.\" other dealings in this Software without prior written authorization
.\" from The Open Group.
.\"
.TH XREFRESH 1 2025-05-31 __xorgversion__
.SH NAME
xrefresh - refresh all or part of an X screen
.SH SYNOPSIS
.B "xrefresh"
[-option ...]
.SH DESCRIPTION
.B Xrefresh
is a simple X program that causes all or part of your screen to be repainted.
This is useful when system messages have messed up your screen.
.B Xrefresh
maps a window on top of the desired area of the screen and then immediately
unmaps it, causing refresh events to be sent to all applications.
By default, a window with no background is used,
causing all applications to repaint \(lqsmoothly.\(rq
However, the various options can be used to indicate that a solid background
(of any color) or the root window background should be used instead.
.SH ARGUMENTS
.TP 10
.B \-white
Use a white background.
The screen just appears to flash quickly, and then repaint.
.TP 10
.B \-black
Use a black background.
This can be somewhat disorienting as everything goes black for a moment.
.TP 10
.B \-solid \fIcolor\fP
Use a solid background of the specified color.  Try green.
.TP 10
.B \-root
Use the root window background.
.TP 10
.B \-none
This is the default.  All of the windows simply repaint.
.TP 10
.B \-geometry \fIWxH+X+Y\fP
Specifies the portion of the screen to be repainted; see
.BR X (__miscmansuffix__).
.TP 10
.B \-display \fIdisplay\fP
This argument allows you to specify the server and screen to refresh; see
.BR X (__miscmansuffix__).
.TP 10
.B \-delay \fIms\fP
Wait for \fIms\fP milliseconds between mapping and unmapping the window.
This can be useful for screens with slow response times, such as e-ink displays.
The default is 0 ms.
.TP 10
.B \-help
This argument prints the program options and exits.
.TP 10
.B \-version
This argument prints the program version and exits.
.SH X DEFAULTS
The
.B xrefresh
program uses the routine
.BR XGetDefault (__libmansuffix__)
to read defaults, so its resource names are all capitalized.
.TP 8
.B Black\fP, \fBWhite\fP, \fBSolid\fP, \fBNone\fP, \fBRoot\fP
Determines what sort of window background to use.
.TP 8
.B Geometry
Determines the area to refresh.  Not very useful.
.SH ENVIRONMENT
.TP 8
.B DISPLAY
To get default host and display number.
.SH SEE ALSO
.BR X (__miscmansuffix__)
.SH BUGS
It should have just one default type for the background.
.SH AUTHORS
Jim Gettys, Digital Equipment Corp., MIT Project Athena
