.\" Copyright (c) 2008, 2025, Oracle and/or its affiliates.
.\"
.\" Permission is hereby granted, free of charge, to any person obtaining a
.\" copy of this software and associated documentation files (the "Software"),
.\" to deal in the Software without restriction, including without limitation
.\" the rights to use, copy, modify, merge, publish, distribute, sublicense,
.\" and/or sell copies of the Software, and to permit persons to whom the
.\" Software is furnished to do so, subject to the following conditions:
.\"
.\" The above copyright notice and this permission notice (including the next
.\" paragraph) shall be included in all copies or substantial portions of the
.\" Software.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
.\" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
.\" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
.\" THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
.\" LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
.\" FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
.\" DEALINGS IN THE SOFTWARE.
.TH XKBVLEDS __appmansuffix__ 2024-05-31 __xorgversion__
.SH NAME
xkbvleds \- display X Keyboard Extension LED state in a window
.SH SYNOPSIS
.nf
\fBxkbvleds\fP [\fB\-indpy\fP \fIname\fP] [\fB\-watch\fP \fIleds\fP] \
[\fB\-intersection\fP] [\fB\-union\fP]
    [\fB+automatic\fP|\fB\-automatic\fP] [\fB+explicit\fP|\fB\-explicit\fP] \
[\fB+name\fP|\fB\-name\fP]
    [\fB+real\fP|\fB\-real\fP] [\fB+virtual\fP|\fB\-virtual\fP]
.fi
.SH DESCRIPTION
This program is used to display the state of LEDs on an XKB keyboard.
It reports the changes in the fundamental components of the XKB state
which includes the effective compatibility state.
The default set of LEDs is \fB\-union +name +automatic +real\fP.
.SH OPTIONS
.TP 8
.B \-indpy \fIname\fP
Mask of LEDs to watch
.TP 8
.B \-watch \fIleds\fP
turn on synchronization
.TP 8
.BR \-automatic " | " +automatic
(Don't) watch automatic LEDs
.TP 8
.BR \-explicit " | " +explicit
(Don't) watch explicit LEDs
.TP 8
.BR \-name " | " +name
(Don't) watch named LEDs
.TP 8
.BR \-real " | " +real
(Don't) watch real LEDs
.TP 8
.BR \-virtual " | " +virtual
(Don't) watch virtual LEDs
.TP 8
.B \-intersection
Watch only LEDs in all desired sets
.TP 8
.B \-union
Watch LEDs in any desired sets
.TP 8
.B \-help
print list of options and exit
.TP 8
.B \-version
print program version and exit
