.\" $XFree86: xc/programs/xf86dga/dga.man,v 3.4 1997/11/08 16:24:37 hohndel Exp $
.\"
.TH dga 1 __vendorversion__
.SH NAME
dga \- test program for the XFree86-DGA extension
.SH SYNOPSIS
.B dga
.SH DESCRIPTION
Dga is a simple test client for the XFree86-DGA extension.  It fills
the screen with a different colour for each key pressed.
It prints some basic framebuffer parameters, and also
keyboard and pointer events to stdout.  To exit, hit the `q' key.
Hitting the `b' key runs a simple benchmark, measuring raw framebuffer
write and read speed (this takes one second each).
.SH AUTHOR
Jon Tombs
