# $OpenBSD: Makefile.bsd-wrapper,v 1.9 2014/12/15 13:17:34 jsg Exp $

.include <bsd.xconf.mk>

.if ${XENOCARA_BUILD_DRI:L} != "yes"
CONFIGURE_ARGS+= --disable-dri
.endif

CONFIGURE_ARGS+= --enable-kms-only

SHARED_LIBS= IntelXvMC 3.0 I810XvMC 3.0

.include <bsd.xorg.mk>
