.\"
.\" Copyright 2004, 2005 X.Org Foundation, LLC
.\" Copyright (c) 1993, 1994, 1996  X Consortium
.\" 
.\" Permission is hereby granted, free of charge, to any person obtaining a
.\" copy of this software and associated documentation files (the "Software"), 
.\" to deal in the Software without restriction, including without limitation 
.\" the rights to use, copy, modify, merge, publish, distribute, sublicense, 
.\" and/or sell copies of the Software, and to permit persons to whom the 
.\" Software furnished to do so, subject to the following conditions:
.\" 
.\" The above copyright notice and this permission notice shall be included in
.\" all copies or substantial portions of the Software.
.\" 
.\" THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
.\" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
.\" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL 
.\" THE X.ORG FOUNDATION BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, 
.\" WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF 
.\" OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE 
.\" SOFTWARE.
.\"
.TH XORGFOUNDATION __miscmansuffix__ __xorgversion__
.SH NAME
XOrgFoundation \- X.Org Foundation information
.SH SYNOPSIS
Release 7.0 of X Version 11 is brought to you by the X.Org Foundation, LLC.
.SH DESCRIPTION
The X.Org Foundation is an independent, not-for-profit 501(c)(3) charity
corporation.  It was formed in 2004 as the successor to the X.Org Group at
The Open Group. The purpose of the X.Org Foundation is to foster the 
development, evolution, and maintenance of the X Window System, a 
comprehensive set of vendor-neutral, system-architecture neutral, 
network-transparent windowing and user interface standards. Membership
in the X.Org Foundation is free and open to anyone. The X.Org Foundation
hosts a public CVS repository of the source code on Freedesktop.Org.
.PP
The X Window System was created in the mid-1980s at the Massachusetts
Institute of Technology.  In 1988, MIT formed a member-funded consortium to
provide the technical and administrative leadership necessary to support
further development of the X Window System.  In 1992, MIT and the membership
decided it was in their best interests to move the consortium out of MIT and
create an independent, stand-alone organization.  All rights to the X Window 
System were assigned by MIT to X Consortium, Inc. on January 1, 1994. On 
December 31, 1996 the X Consortium, Inc. closed its doors and all rights 
to the X Window System were assigned to The Open Group (then known as the
Open Software Foundation.)
.PP
.SH "ADDRESSES"
The X.Org Foundation's web site is http://www.x.org/
.PP
The X.Org Foundation's public ftp site is ftp://ftp.x.org/
.PP
Information about the X.Org Foundation CVS repository is on the 
Freedesktop.Org web site at http://www.freedesktop.org/Software/xorg
.fi
