#	$OpenBSD: Makefile,v 1.1.1.1 2009/06/06 17:55:01 matthieu Exp $

SUBDIR=		digital_vndr sgi_vndr

XKB_SUBDIR=	keycodes
DIR_DATA=	keycodes.dir

DATA=	aliases \
	amiga \
	ataritt \
	evdev \
	fujitsu \
	hp \
	ibm \
	macintosh \
	sony \
	sun \
	xfree86 \
	xfree98 \
	README

.include <bsd.xorg.mk>
.include <bsd.subdir.mk>
