#	$OpenBSD: Makefile,v 1.4 2012/10/06 15:41:12 shadchin Exp $

SUBDIR=		digital_vndr sgi_vndr

XKB_SUBDIR=	geometry

DATA=	amiga ataritt chicony dell everex fujitsu hhk hp keytronic kinesis \
	macintosh microsoft nec nokia northgate pc sanwa sony thinkpad sun \
	typematrix winbook README

.include <bsd.xorg.mk>
.include <bsd.subdir.mk>
