#!/bin/sh
# Assign ownership of the console to the invoking user
# $Xorg: GiveConsole,v 1.3 2000/08/17 19:54:17 cpqbld Exp $
# $OpenBSD: GiveConsole,v 1.2 2006/11/28 15:41:12 matthieu Exp $
#
# By convention, both xconsole and xterm -C check that the
# console is owned by the invoking user and is readable before attaching
# the console output.  This way a random user can invoke xterm -C without
# causing serious grief.
#
chown $USER /dev/console
/usr/X11R6/bin/sessreg -a -l $DISPLAY -u none -x /usr/X11R6/lib/X11/xdm/Xservers $USER
