# $OpenBSD: Makefile.bsd-wrapper,v 1.4 2019/05/10 11:44:39 schwarze Exp $

CONFIGURE_ARGS += --without-fop --without-xmlto

beforeinstall:
	${INSTALL} ${INSTALL_COPY} -o ${MANOWN} -g ${MANGRP} -m ${MANMODE} \
		${.CURDIR}/doc/xtrans.3 ${DESTDIR}${MANDIR}3

# maintainer target, not used duing build or install
mdoc:
	docbook2mdoc -s 3 ${.CURDIR}/doc/xtrans.xml > ${.CURDIR}/doc/xtrans.3

.PHONY: mdoc

.include <bsd.xorg.mk>
