/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#ifdef __sparc64__
#define ASM_HAVE_FUNC_DIRECTIVE 1
#endif

#ifdef __arm__
#define ASM_HAVE_SYNTAX_UNIFIED 1
#endif

#define HAVE_ALARM 1

#if defined(__GNUC__) && __GNUC__ < 4
#undef HAVE_BUILTIN_CLZ		/* gcc3 doesn't have __builtin_clz */
#else
#define HAVE_BUILTIN_CLZ 1
#endif

#define HAVE_FEDIVBYZERO 1

#undef HAVE_FEENABLEEXCEPT

#define HAVE_FENV_H 1

#if defined(__amd64__) || defined(__i386__) || defined(__powerpc__) \
	|| defined(__arm__)
#define HAVE_GCC_VECTOR_EXTENSIONS 1
#endif

#define HAVE_GETPAGESIZE 1

#define HAVE_GETTIMEOFDAY 1

#define HAVE_MMAP 1

#define HAVE_MPROTECT 1

#define HAVE_POSIX_MEMALIGN 1

#define HAVE_PTHREADS 1

#define HAVE_SIGACTION 1

#define HAVE_SYS_MMAN_H 1

#define HAVE_UNISTD_H 1

#define PACKAGE pixman

#ifdef _LP64
#define SIZEOF_LONG 8
#else
#define SIZEOF_LONG 4
#endif

#if defined(__amd64__) || defined(__i386__) || defined(__powerpc__) \
	|| defined(__arm__)
#define TLS __thread
#endif

#define TOOLCHAIN_SUPPORTS_ATTRIBUTE_CONSTRUCTOR 1

#define USE_GCC_INLINE_ASM 1

#if defined(__amd64__) || defined(__i386__)
#define USE_SSE2 1

#define USE_SSSE3 1

#define USE_X86_MMX 1
#endif

#if defined(__arm__)
#define USE_ARM_NEON 1

#define USE_ARM_SIMD 1
#endif

#if defined(__powerpc__)
#define USE_VMX 1
#endif

#if defined(__sparc64__) || defined(__powerpc__)
#define WORDS_BIGENDIAN 1
#endif
