#	$OpenBSD: Makefile,v 1.4 2010/05/08 14:15:29 matthieu Exp $

.include <bsd.own.mk>

FILES=	automake.dep bsd.xconf.mk bsd.xorg.mk

all:

install::
	${INSTALL_DATA} ${FILES} ${DESTDIR}${X11BASE}/share/mk

.include <bsd.xorg.mk>
