# $OpenBSD: Makefile.bsd-wrapper,v 1.19 2013/02/19 20:56:17 brad Exp $

.include <bsd.own.mk>

SHARED_LIBS=	pixman-1 28.0

.if ${MACHINE_ARCH} == arm
CONFIGURE_ARGS +=  --disable-arm-simd --disable-arm-neon
.endif

.include <bsd.xorg.mk>
