# $OpenBSD: Makefile.bsd-wrapper,v 1.15 2011/07/24 13:05:47 matthieu Exp $

.include <bsd.own.mk>

SHARED_LIBS=	pixman-1 22.2

.if ${MACHINE_ARCH} == arm
CONFIGURE_ARGS +=  --disable-arm-simd --disable-arm-neon
.endif

.if ${MACHINE_ARCH} == m68k
CFLAGS += -fno-regmove
CONFIGURE_ARGS += --cache-file=/dev/null
.endif

.include <bsd.xorg.mk>
