# $OpenBSD: Makefile.bsd-wrapper,v 1.10 2010/05/11 18:51:21 espie Exp $

.include <bsd.own.mk>

SHARED_LIBS=	pixman-1 16.6

.if ${MACHINE} == amd64 && !${COMPILER_VERSION:L:Mgcc4*}
CONFIGURE_ARGS += --disable-sse2
.endif

.if ${MACHINE_ARCH} == arm
CONFIGURE_ARGS +=  --disable-arm-simd --disable-arm-neon
.endif

.include <bsd.xorg.mk>
