#	$OpenBSD: Makefile,v 1.4 2008/06/22 17:37:35 matthieu Exp $


.include <bsd.xorg.mk>

SUBDIR=	config internal


INCSDIR=${X11BASE}/include/freetype2/freetype

INCS=	freetype.h ftbbox.h ftbdf.h ftbitmap.h \
	ftcache.h ftchapters.h ftcid.h fterrdef.h fterrors.h ftgasp.h \
	ftglyph.h ftgzip.h ftimage.h ftincrem.h ftlcdfil.h ftlist.h \
	ftlzw.h ftmac.h ftmm.h ftmodapi.h ftmoderr.h ftoutln.h ftpfr.h \
	ftrender.h ftsizes.h ftsnames.h ftstroke.h ftsynth.h \
	ftsystem.h fttrigon.h fttypes.h ftwinfnt.h ftxf86.h \
	t1tables.h ttnameid.h tttables.h tttags.h ttunpat.h

.include "Makefile.inc"
.include <bsd.subdir.mk>

