# $OpenBSD: Makefile,v 1.1 2012/08/07 21:10:35 matthieu Exp $

X11BASE?= /usr/X11R6
MANDIR?= ${X11BASE}/man/man

MAN += GLwCreateMDrawingArea.3 glwcreatemdrawingarea.gl
MAN += GLwDrawingArea.3 glwdrawingarea.gl
MAN += GLwDrawingAreaMakeCurrent.3 glwdrawingareamakecurrent.gl
MAN += GLwDrawingAreaSwapBuffers.3 glwdrawingareaswapbuffers.gl

LINKS += GLwDrawingArea.3 GLwMDrawingArea.3

.include "../Makefile.inc"
.include <bsd.xorg.mk>
