# $OpenBSD: Makefile.bsd-wrapper,v 1.3 2006/12/04 21:09:59 matthieu Exp $

all:	includes
	$(MAKE)

depend:
	if [ ${.OBJDIR} != ${.CURDIR} ]; then lndir ${.CURDIR}; fi
	if [ -x $(X11BASE)/bin/xmkmf ]; then \
		$(X11BASE)/bin/xmkmf ;\
	fi

install:
	$(MAKE) install.man

.include <bsd.xorg.mk>
