.\" $XFree86: xc/programs/Xserver/hw/xfree86/drivers/v4l/v4l.man,v 1.2 2001/01/27 18:20:55 dawes Exp $ 
.\" shorthand for double quote that works everywhere.
.ds q \N'34'
.TH V4L __drivermansuffix__ __vendorversion__
.SH NAME
v4l \- video4linux driver
.SH SYNOPSIS
.nf
.B "Section \*qModule\*q"
\ \ ...
.B "  Load \*qv4l\*q"
.B EndSection
.fi
.SH DESCRIPTION
.B v4l 
is an __xservername__ driver for video4linux cards.  It provides a Xvideo
extension port for video overlay.  Just add the driver to the module
list within the module section of your __xconfigfile__ file if you want
to use it.  There are no config options.
.P
Note that the the extmod module is also required for the Xvideo
support (and lots of other extensions too).
.SH SUPPORTED HARDWARE
The
.B v4l
driver works with every piece of hardware which is supported by a
video4linux (kernel-) device driver and is able to handle video
overlay.
.P
bt848/bt878-based TV cards are the most popular hardware these
days.
.SH CONFIGURATION DETAILS
Please refer to __xconfigfile__(__filemansuffix__) for general configuration
details.  This section only covers configuration details specific to this
driver.
.SH "SEE ALSO"
__xservername__(__appmansuffix__), __xconfigfile__(__filemansuffix__), xorgconfig(__appmansuffix__), Xserver(__appmansuffix__), X(__miscmansuffix__)
.SH AUTHORS
Authors include: Gerd Knorr <kraxel@bytesex.org>
