#	$OpenBSD: Makefile,v 1.13 2016/06/28 16:49:22 shadchin Exp $

SUBDIR=		digital_vndr fujitsu_vndr hp_vndr jolla_vndr macintosh_vndr \
		nec_vndr nokia_vndr sgi_vndr sharp_vndr sony_vndr sun_vndr \
		xfree68_vndr

XKB_SUBDIR=	symbols

DATA=	af al am apl ara at az ba bd be bg bn br brai bt bw by ca cd ch cm cn \
	cz de dk dz ee es et eu epo fi fo fr gb ge gh gn gr hr hu id ie il in \
	iq ir is it jp ke kg kh kr kz la latam latin lk lt lv ma mao md me mk \
	ml mm mn mt mv my ng nl no np pc ph pk pl pt ro rs ru se si sk sn sy \
	tg th terminate tj tm tw tr tz ua us uz vn za altwin capslock compose \
	ctrl empty eurosign rupeesign group inet keypad kpdl level3 level5 \
	nbsp olpc shift srvr_ctrl typo

.include <bsd.xorg.mk>
.include <bsd.subdir.mk>
