.\" $XdotOrg: $
.\" $XFree86: xc/programs/xvinfo/xvinfo.man,v 1.2 2001/01/24 00:06:51 dawes Exp $
.\"
.TH xvinfo __appmansuffix__ __vendorversion__
.SH NAME
xvinfo - Print out X-Video extension adaptor information
.SH SYNOPSIS
.B "xvinfo"
[-display \fIdisplayname\fP] 
.SH DESCRIPTION
.PP
.B xvinfo
prints out the capabilities of any video adaptors associated
with the display that are accesible through the X-Video extension. 
.SH OPTIONS
.PP
.TP 8
.B "-display \fIdisplay\fP"
This argument allows you to specify the server to query; see \fIX(__miscmansuffix__)\fP.
.SH ENVIRONMENT
.PP
.TP 8
.B DISPLAY
This variable may be used to specify the server to query.

.SH SEE ALSO
xdpyinfo(1)
.SH AUTHORS
Mark Vojkovich
