.TH XVINFO __appmansuffix__ 2025-04-12 __vendorversion__
.SH NAME
xvinfo - Print out X-Video extension adaptor information
.SH SYNOPSIS
.B "xvinfo"
[\fB\-display\fP \fIdisplayname\fP] [\fB\-short\fP]
.PP
.B "xvinfo"
\fB\-help\fP | \fB\-version\fP
.SH DESCRIPTION
.B xvinfo
prints out the capabilities of any video adaptors associated
with the display that are accessible through the X\-Video extension.
.SH OPTIONS
.TP 8
.B "\-display \fIdisplay\fP"
This argument allows you to specify the server to query; see \fIX(__miscmansuffix__)\fP.
.TP 8
.B "\-short"
Output less details, to reduce the amount of text.
.TP 8
.B "\-help"
Output program usage, then exit.
.TP 8
.B "\-version"
Output program version, then exit.
.SH ENVIRONMENT
.TP 8
.B DISPLAY
This variable may be used to specify the server to query.
.SH SEE ALSO
.BR X (__miscmansuffix__),
.BR xdpyinfo (__appmansuffix__),
.BR xwininfo (__appmansuffix__),
.BR xdriinfo (__appmansuffix__),
.BR glxinfo (__appmansuffix__),
.BR xprop (__appmansuffix__)
.SH AUTHORS
Mark Vojkovich
