
# $OpenBSD: Makefile.bsd-wrapper,v 1.6 2010/11/11 10:54:03 matthieu Exp $

SHARED_LIBS=	Xi 11.0

CONFIGURE_ARGS+=	--without-xmlto --without-asciidoc --without-fop \
			--disable-specs

.include <bsd.xorg.mk>
