# $OpenBSD: Makefile.bsd-wrapper,v 1.10 2021/11/11 08:58:33 matthieu Exp $

SHARED_LIBS=	Xi 12.2

CONFIGURE_ARGS+=	--without-xmlto --without-asciidoc --without-fop \
			--disable-specs

.include <bsd.xorg.mk>
