# $OpenBSD: Makefile.bsd-wrapper,v 1.7 2012/06/11 19:24:48 matthieu Exp $

SHARED_LIBS=	Xi 11.1

CONFIGURE_ARGS+=	--without-xmlto --without-asciidoc --without-fop \
			--disable-specs

.include <bsd.xorg.mk>
