/* 
 * This file is generated automatically from the default
 * twm bindings file system.twmrc by the twm Imakefile.
 */

unsigned char *defTwmrc[] = {
    (unsigned char *) "",
    (unsigned char *) "NoGrabServer",
    (unsigned char *) "RestartPreviousState",
    (unsigned char *) "DecorateTransients",
    (unsigned char *) "TitleFont \"-adobe-helvetica-bold-r-normal--*-120-*-*-*-*-*-*\"",
    (unsigned char *) "ResizeFont \"-adobe-helvetica-bold-r-normal--*-120-*-*-*-*-*-*\"",
    (unsigned char *) "MenuFont \"-adobe-helvetica-bold-r-normal--*-120-*-*-*-*-*-*\"",
    (unsigned char *) "IconFont \"-adobe-helvetica-bold-r-normal--*-100-*-*-*-*-*-*\"",
    (unsigned char *) "IconManagerFont \"-adobe-helvetica-bold-r-normal--*-100-*-*-*\"",
    (unsigned char *) "",
    (unsigned char *) "Color",
    (unsigned char *) "{",
    (unsigned char *) "    BorderColor \"slategrey\"",
    (unsigned char *) "    DefaultBackground \"rgb:2/a/9\"",
    (unsigned char *) "    DefaultForeground \"gray85\"",
    (unsigned char *) "    TitleBackground \"rgb:2/a/9\"",
    (unsigned char *) "    TitleForeground \"gray85\"",
    (unsigned char *) "    MenuBackground \"rgb:2/a/9\"",
    (unsigned char *) "    MenuForeground \"gray85\"",
    (unsigned char *) "    MenuBorderColor \"slategrey\"",
    (unsigned char *) "    MenuTitleBackground \"gray70\"",
    (unsigned char *) "    MenuTitleForeground \"rgb:2/a/9\"",
    (unsigned char *) "    IconBackground \"rgb:2/a/9\"",
    (unsigned char *) "    IconForeground \"gray85\"",
    (unsigned char *) "    IconBorderColor \"gray85\"",
    (unsigned char *) "    IconManagerBackground \"rgb:2/a/9\"",
    (unsigned char *) "    IconManagerForeground \"gray85\"",
    (unsigned char *) "}",
    (unsigned char *) "",
    (unsigned char *) "MoveDelta 3",
    (unsigned char *) "Function \"move-or-lower\" { f.move f.deltastop f.lower }",
    (unsigned char *) "Function \"move-or-raise\" { f.move f.deltastop f.raise }",
    (unsigned char *) "Function \"move-or-iconify\" { f.move f.deltastop f.iconify }",
    (unsigned char *) "",
    (unsigned char *) "Button1 = : root : f.menu \"defops\"",
    (unsigned char *) "",
    (unsigned char *) "Button1 = m : window|icon : f.function \"move-or-lower\"",
    (unsigned char *) "Button2 = m : window|icon : f.iconify",
    (unsigned char *) "Button3 = m : window|icon : f.function \"move-or-raise\"",
    (unsigned char *) "",
    (unsigned char *) "Button1 = : title : f.function \"move-or-raise\"",
    (unsigned char *) "Button2 = : title : f.raiselower",
    (unsigned char *) "",
    (unsigned char *) "Button1 = : icon : f.function \"move-or-iconify\"",
    (unsigned char *) "Button2 = : icon : f.iconify",
    (unsigned char *) "",
    (unsigned char *) "Button1 = : iconmgr : f.iconify",
    (unsigned char *) "Button2 = : iconmgr : f.iconify",
    (unsigned char *) "",
    (unsigned char *) "menu \"defops\"",
    (unsigned char *) "{",
    (unsigned char *) "\"Twm\"	f.title",
    (unsigned char *) "\"Iconify\"	f.iconify",
    (unsigned char *) "\"Resize\"	f.resize",
    (unsigned char *) "\"Move\"		f.move",
    (unsigned char *) "\"Raise\"		f.raise",
    (unsigned char *) "\"Lower\"		f.lower",
    (unsigned char *) "\"\"		f.nop",
    (unsigned char *) "\"Focus\"		f.focus",
    (unsigned char *) "\"Unfocus\"	f.unfocus",
    (unsigned char *) "\"Show Iconmgr\"	f.showiconmgr",
    (unsigned char *) "\"Hide Iconmgr\"	f.hideiconmgr",
    (unsigned char *) "\"\"		f.nop",
    (unsigned char *) "\"Xterm\"		f.exec \"exec xterm &\"",
    (unsigned char *) "\"\"		f.nop",
    (unsigned char *) "\"Kill\"		f.destroy",
    (unsigned char *) "\"Delete\"	f.delete",
    (unsigned char *) "\"\"		f.nop",
    (unsigned char *) "\"Restart\"	f.restart",
    (unsigned char *) "\"Exit\"		f.quit",
    (unsigned char *) "}",
    (unsigned char *) 0 };
