.\" $XConsortium: xgc.man,v 1.6 94/04/17 20:45:31 gildea Exp $
.\"
.\" $XFree86$
.\"
.TH XGC 1 __xorgversion__
.SH NAME
xgc - X graphics demo
.SH SYNOPSIS
.ta 8n
\fBxgc\fP [-\fItoolkitoption\fP ...]
.SH DESCRIPTION
The
.I xgc
program demonstrates various features of the X graphics primitives.
Try the buttons, see what they do; we haven't the time to document
them, perhaps you do?
.SH OPTIONS
.I Xgc
accepts all of the standard X Toolkit command line options.
.SH X DEFAULTS
This program accepts the usual defaults for toolkit applications.
.SH ENVIRONMENT
.PP
.TP 8
.B DISPLAY
to get the default host and display number.
.TP 8
.B XENVIRONMENT
to get the name of a resource file that overrides the global resources
stored in the RESOURCE_MANAGER property.
.SH "SEE ALSO"
X(__miscmansuffix__)
.SH BUGS
This program isn't really finished yet.
.br
See \fIX(__miscmansuffix__)\fP for a full statement of rights and permissions.
.SH AUTHORS
Dan Schmidt, MIT
