#	$OpenBSD: Makefile,v 1.4 2014/01/12 15:08:26 matthieu Exp $


.include <bsd.xorg.mk>

SUBDIR=	config


INCSDIR=${X11BASE}/include/freetype2

INCS=	freetype.h ftadvanc.h ftbbox.h ftbdf.h ftbitmap.h ftbzip2.h \
	ftcache.h ftchapters.h ftcffdrv.h ftcid.h fterrdef.h fterrors.h \
	ftgasp.h ftglyph.h ftgxval.h ftgzip.h ftimage.h ftincrem.h \
	ftlcdfil.h ftlist.h ftlzw.h ftmac.h ftmm.h ftmodapi.h ftmoderr.h \
	ftoutln.h ftotval.h ftpfr.h ftrender.h ftsizes.h ftsnames.h \
	ftstroke.h ftsynth.h ftsystem.h fttrigon.h fttypes.h ftwinfnt.h \
	ftxf86.h t1tables.h ttnameid.h tttables.h tttags.h ttunpat.h

.include "Makefile.inc"
.include <bsd.subdir.mk>

