/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Name of package */
#define PACKAGE "beforelight"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "https://bugs.freedesktop.org/enter_bug.cgi?product=xorg"

/* Define to the full name of this package. */
#define PACKAGE_NAME "beforelight"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "beforelight 1.0.1"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "beforelight"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.0.1"

/* Version number of package */
#define VERSION "1.0.1"
