#	$OpenBSD: Makefile,v 1.7 2016/05/29 11:57:11 dcoppa Exp $
.include <bsd.xorg.mk>

SUBDIR=	services

INCSDIR=${X11BASE}/include/freetype2/freetype/internal

INCS=	autohint.h ftcalc.h ftdebug.h ftdriver.h ftgloadr.h fthash.h \
	ftmemory.h ftobjs.h ftpic.h ftrfork.h ftserv.h ftstream.h \
	fttrace.h ftvalid.h internal.h psaux.h pshints.h \
	sfnt.h t1types.h tttypes.h

.include <bsd.subdir.mk>
