# $OpenBSD: Makefile.bsd-wrapper,v 1.5 2011/03/09 19:53:24 matthieu Exp $
.include <bsd.xconf.mk>

.if ${XENOCARA_USE_XKEYBOARD_CONFIG:L} != "yes"
CONFIGURE_ARGS= --datadir=/etc
.endif

.include <bsd.xorg.mk>
