#	$OpenBSD: Makefile,v 1.3 2013/10/26 17:49:57 shadchin Exp $

XKB_SUBDIR=	symbols/sun_vndr

DATA=	ara be br ca ch cz de dk ee es fi fr gb gr it jp kr lt lv nl no pl pt \
	ro ru se sk solaris tr tw ua us

.include <bsd.xorg.mk>
