.TH XvFreeEncodingInfo __libmansuffix__ __vendorversion__
.SH Name
XvFreeEncodingInfo \- free encoding information 
.\"
.SH Syntax
\fBXvFreeEncodingInfo(XvEncodingInfo *\fIp_encoding_info\fR)"
.SH Arguments
.\"
.IP \fIp_encoding_info\fR 8
Pointer to where the encoding information is located. 
.\"
.SH Description
.\"
XvFreeEncodingInfo(__libmansuffix__) frees encoding information that 
was returned by XvQueryEncodings(__libmansuffix__).  The data structure
used for encoding information is defined in the
reference page for XvQueryEncodings(__libmansuffix__).
.SH See Also
.\"
XvQueryEncodings(__libmansuffix__)
.br
