.TH XvFreeAdaptorInfo __libmansuffix__ __vendorversion__
.SH Name
XvFreeAdaptorInfo \- free adaptor information 
.\"
.SH Syntax
\fBXvFreeAdaptorInfo(XvAdaptorInfo *\fIp_adaptor_info\fR)
.SH Arguments
.\"
.IP \fIp_adaptor_info\fR 8
Pointer to where the adaptor information is located. 
.\"
.SH Description
.\"
XvFreeAdaptorInfo(__libmansuffix__) frees adaptor information that 
was returned by XvQueryAdaptors(__libmansuffix__).  The data structure
used for adaptor information is defined in the
reference page for XvQueryAdaptors(__libmansuffix__).
.SH See Also
.\"
XvQueryAdaptors(__libmansuffix__), XvFreeEncodingInfo(__libmansuffix__)
.br
