.TH XvSelectVideoNotify __libmansuffix__ __vendorversion__
.\" $XFree86: xc/doc/man/Xv/XvSelectVideoNotify.man,v 1.5 2001/01/27 18:20:36 dawes Exp $
.SH Name
XvSelectVideoNotify \- enable or disable VideoNotify events
.\"
.SH Syntax
\fB#include\fI <X11/extensions/Xvlib.h>\fR
.sp 1l
\fBXvSelectVideoNotify(\fIdpy, drawable, onoff\fR)
.sp 1l
\fBregister Display \fI*dpy\fR;
.br
\fBDrawable \fIdrawable\fR;
.br
\fBBool \fIonoff\fR;
.SH Arguments
.\"
.IP \fIdpy\fR 15
Specifies the connection to the X server.
.IP \fIdrawable\fR 15
Defines the drawable in which video activity is to be reported.
.IP \fIonoff\fR 15
Selects whether video notification is enabled or disabled.
.\"
.SH Description
XvSelectVideoNotify(__libmansuffix__) enables or disables events to be reported for 
video activity in a drawable.
.\"
.SH Returned Values
.IP [Success] 8
Returned if XvSelectVideoNotify(__libmansuffix__) completed successfully.
.IP [XvBadExtension] 8
Returned if the Xv extension is unavailable.
.IP [XvBadAlloc] 8
Returned if XvSelectVideoNotify(__libmansuffix__) failed to allocate memory to process
the request.
.SH Diagnostics
.IP [BadDrawable] 8
Generated if the requested drawable does not exist.
.SH See Also
.\"
XvVideoNotify
.br
