#	$OpenBSD: Makefile,v 1.1.1.1 2009/06/06 17:55:01 matthieu Exp $

XKB_SUBDIR=	keymap/sgi_vndr

DATA=	be bg ca \
	ch cz de \
	dk dvorak \
	es fi \
	fr gb \
	hu it jp \
	no pl pt \
	ru se sk \
	th us

.include <bsd.xorg.mk>

