# $OpenBSD: Makefile.bsd-wrapper,v 1.12 2010/05/18 19:37:30 matthieu Exp $
.include <bsd.xconf.mk>

SHARED_LIBS=	X11 13.0

CONFIGURE_ARGS= --enable-tcp-transport --enable-unix-transport --enable-ipv6

.if ${XENOCARA_BUILD_XCB:L} == "no"
CONFIGURE_ARGS+= --without-xcb
.endif

.if ${XENOCARA_HAVE_SHARED_LIBS:L} == "no"
CONFIGURE_ARGS+= --disable-loadable-xcursor
.endif

.include <bsd.xorg.mk>
