# $OpenBSD: Makefile.bsd-wrapper,v 1.20 2013/05/23 22:42:07 matthieu Exp $
.include <bsd.xconf.mk>

SHARED_LIBS=	X11 15.2

CONFIGURE_ARGS= --enable-tcp-transport --enable-unix-transport --enable-ipv6 \
	--disable-composecache \
	--without-xmlto --without-fop --without-xsltproc

.if ${XENOCARA_HAVE_SHARED_LIBS:L} == "no"
CONFIGURE_ARGS+= --disable-loadable-xcursor
.endif

.include <bsd.xorg.mk>
