# $OpenBSD: Makefile.bsd-wrapper,v 1.25 2019/08/04 13:33:46 matthieu Exp $
.include <bsd.xconf.mk>

SHARED_LIBS=	X11 17.0 X11_xcb 2.0

CONFIGURE_ARGS= --enable-tcp-transport --enable-unix-transport --enable-ipv6 \
	--disable-composecache \
	--without-xmlto --without-fop --without-xsltproc

.include <bsd.xorg.mk>
