#	$OpenBSD: Makefile,v 1.5 2018/09/11 19:34:56 matthieu Exp $

SUBDIR=\
	libxcb \
	libxcb-composite \
	libxcb-damage \
	libxcb-dpms \
	libxcb-dri2 \
	libxcb-dri3 \
	libxcb-glx \
	libxcb-present \
	libxcb-randr \
	libxcb-record \
	libxcb-render \
	libxcb-res \
	libxcb-screensaver \
	libxcb-shape \
	libxcb-shm \
	libxcb-sync \
	libxcb-xf86dri \
	libxcb-xfixes \
	libxcb-xinerama \
	libxcb-xinput \
	libxcb-xkb \
	libxcb-xtest \
	libxcb-xv \
	libxcb-xvmc

.include <bsd.subdir.mk>
.include <bsd.xorg.mk>
