#	$OpenBSD: Makefile,v 1.1.1.1 2009/05/22 16:09:01 matthieu Exp $

SUBDIR=\
	libxcb \
	libxcb-composite \
	libxcb-damage \
	libxcb-dpms \
	libxcb-glx \
	libxcb-randr \
	libxcb-record \
	libxcb-render \
	libxcb-res \
	libxcb-screensaver \
	libxcb-shape \
	libxcb-shm \
	libxcb-sync \
	libxcb-xevie \
	libxcb-xf86dri \
	libxcb-xfixes \
	libxcb-xinerama \
	libxcb-xprint \
	libxcb-xtest \
	libxcb-xv \
	libxcb-xvmc


.include <bsd.subdir.mk>
.include <bsd.xorg.mk>
