# $OpenBSD: Makefile.bsd-wrapper,v 1.4 2016/10/02 09:30:18 tb Exp $

afterinstall:
	cd ${DESTDIR}${X11BASE}/man/man4 ; ln -sf mousedrv.4 mouse.4 ; \
		chown -h ${MANOWN}:${MANGRP} mouse.4

.include <bsd.xorg.mk>
