# $OpenBSD: Makefile.bsd-wrapper,v 1.9 2023/07/03 09:20:46 matthieu Exp $

SHARED_LIBS=	Xt 11.1

CONFIGURE_ARGS= --with-appdefaultdir=/usr/X11R6/share/X11/app-defaults \
	--without-xmlto --without-fop --without-xsltproc --without-glib

.include <bsd.xorg.mk>
