# $OpenBSD: Makefile.bsd-wrapper,v 1.6 2012/03/10 16:49:42 matthieu Exp $

SHARED_LIBS=	Xt 10.1

CONFIGURE_ARGS= --with-appdefaultdir=/etc/X11/app-defaults \
	--without-xmlto --without-fop --without-xsltproc --without-glib

.include <bsd.xorg.mk>
